[package]
name = "lif_interpreter"
version = "0.1.0"
edition = "2021"

[features]
default = []
os-poll = []
net = []

[dependencies]
lazy_static = "1.4"
antlr-rust = "0.2.2"
mio = {version = "0.8", features = ["net","os-poll"]}